/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconAbout: typeof import('./src/components/icons/iconAbout.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDark: typeof import('./src/components/icons/iconDark.vue')['default']
    IconDocs: typeof import('./src/components/icons/iconDocs.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconFriend: typeof import('./src/components/icons/iconFriend.vue')['default']
    IconFriendLink: typeof import('./src/components/icons/iconFriendLink.vue')['default']
    IconHome: typeof import('./src/components/icons/iconHome.vue')['default']
    IconLight: typeof import('./src/components/icons/iconLight.vue')['default']
    IconMore: typeof import('./src/components/icons/iconMore.vue')['default']
    IconOpenAI: typeof import('./src/components/icons/iconOpenAI.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconThink: typeof import('./src/components/icons/iconThink.vue')['default']
    IconTimeLine: typeof import('./src/components/icons/iconTimeLine.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Svg: typeof import('./src/components/Svg.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
