/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    IconAbout: typeof import('./src/components/icons/iconAbout.vue')['default']
    IconDark: typeof import('./src/components/icons/iconDark.vue')['default']
    IconDocs: typeof import('./src/components/icons/iconDocs.vue')['default']
    IconFriendLink: typeof import('./src/components/icons/iconFriendLink.vue')['default']
    IconHome: typeof import('./src/components/icons/iconHome.vue')['default']
    IconHomeMobile: typeof import('./src/components/icons/iconHomeMobile.vue')['default']
    IconLight: typeof import('./src/components/icons/iconLight.vue')['default']
    IconMore: typeof import('./src/components/icons/iconMore.vue')['default']
    IconOpenAI: typeof import('./src/components/icons/iconOpenAI.vue')['default']
    IconTimeLine: typeof import('./src/components/icons/iconTimeLine.vue')['default']
    IconUser: typeof import('./src/components/icons/iconUser.vue')['default']
    InnerLoading: typeof import('./src/components/InnerLoading.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signature: typeof import('./src/components/Signature.vue')['default']
  }
}
