/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    IconAbout: typeof import('./src/components/icons/iconAbout.vue')['default']
    IconDark: typeof import('./src/components/icons/iconDark.vue')['default']
    IconDocs: typeof import('./src/components/icons/iconDocs.vue')['default']
    IconFriendLink: typeof import('./src/components/icons/iconFriendLink.vue')['default']
    IconHome: typeof import('./src/components/icons/iconHome.vue')['default']
    IconLight: typeof import('./src/components/icons/iconLight.vue')['default']
    IconMore: typeof import('./src/components/icons/iconMore.vue')['default']
    IconOpenAI: typeof import('./src/components/icons/iconOpenAI.vue')['default']
    IconThink: typeof import('./src/components/icons/iconThink.vue')['default']
    IconTimeLine: typeof import('./src/components/icons/iconTimeLine.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    'Loading.': typeof import('./src/components/Loading..vue')['default']
    Loading1: typeof import('./src/components/Loading1.vue')['default']
    Loading2: typeof import('./src/components/Loading2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
